onEvent('recipes', event => {
  event.remove({ output: 'enigmaticlegacy:cosmic_cake' })
  event.remove({ output: 'ars_nouveau:novice_spell_book' })
  event.remove({ output: 'ars_nouveau:apprentice_spell_book' })
  event.remove({ output: 'ars_nouveau:archmage_spell_book' })
  event.remove({ output: 'enigmaticlegacy:the_cube' })
  event.remove({ output: 'ars_nouveau:scribes_table' })
  event.remove({ output: 'ars_nouveau:enchanting_apparatus' })
  event.remove({ output: 'ars_nouveau:imbuement_chamber' })
  event.remove({ output: 'ars_nouveau:ritual_sunrise' })
  event.remove({ output: 'playingcards:poker_chip_white'})
  event.remove({ output: 'playingcards:poker_chip_red'})
  event.remove({ output: 'playingcards:poker_chip_blue'})
  event.remove({ output: 'playingcards:poker_chip_black'})
  event.remove({ output: 'playingcards:poker_chip_green'})
})