onEvent('block.registry', event => {
    event.create('drome_ore')
        .material('stone')
        .hardness(5)
        .resistance(8)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .requiresTool(true)
        .item(itemBuilder => {}) 
        .displayName('梦穹金矿')

        event.create('drome_block')
        .material('metal')
        .hardness(5)
        .resistance(8)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .requiresTool(true)
        .displayName('梦穹金块')

        event.create('raw_drome_block')
        .material('metal')
        .hardness(5)
        .resistance(8)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .requiresTool(true)
        .displayName('粗梦穹金块')

        event.create('wheat_block')
        .material('metal')
        .hardness(2)
        .resistance(3)
        .requiresTool(false)
        .displayName('§e麦块')
})